version: '3'
services:
  backend:
    image: boleknowak/wowee-link-api:latest
    ports:
      - ${API_PORT}:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
  frontend:
    image: boleknowak/wowee-link:latest
    ports:
      - ${FRONTEND_PORT}:3000
    environment:
      - API_URL=http://backend:8000
